apiVersion: v1
kind: ConfigMap
metadata:
  name: loja-config
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "loja_user"
  DB_NAME: "loja_db"
---
apiVersion: v1
kind: Secret
metadata:
  name: loja-secrets
type: Opaque
stringData:
  # O uso de stringData é mais prático pois evita conversão manual para base64
  DB_PASSWORD: "sua_senha_segura"